version: '3.3'
services:
  hwc:
    # container_name: hwc
    build: .
    restart: always
    command: uwsgi hwc_server.ini
    environment:
      APP_DEBUG: "False"
      MONGODB_DATABASE: ${DB}
      MONGODB_PORT: 27017
      MONGODB_HOSTNAME: mongodb
    networks:
      - net
    ports:
      - ${APP_EXTERNAL_PORT}:5050
    volumes:
      - hwc-volume:/data/hwc

  mongodb:
    image: mongo:4.4.6
    # container_name: mongodb
    restart: always
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /tmp/logs
    volumes:
      - hwc-volume:/data/db
    networks:
      - net
    ports:
      - ${DB_EXTERNAL_PORT}:27017

  mongodb-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    volumes:
      - hwc-volume:/data/db
    networks:
      - net

volumes:
  hwc-volume:
    driver: local

networks:
  net:
    driver: bridge
